server {
    listen 8080 default_server;
    listen [::]:8080 default_server;
    server_name debdesktop.duckdns.org _;

    # Web-based SSH terminal (shellinabox)
    location /terminal/ {
        proxy_pass http://127.0.0.1:4200/;
        proxy_http_version 1.1;
        proxy_set_header Host debdesktop.duckdns.org;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Trading web app
    location / {
        proxy_pass http://127.0.0.1:8090;
        proxy_http_version 1.1;
        proxy_set_header Host debdesktop.duckdns.org;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
